language: generic
jobs:
  include:
    - os: linux
      dist: xenial
      sudo: required
      install:
        - cd $HOME
        - sudo apt-get install -y clang libicu-dev
        - wget -q -O swift.tar.gz https://swift.org/builds/swift-5.0.3-release/ubuntu1604/swift-5.0.3-RELEASE/swift-5.0.3-RELEASE-ubuntu16.04.tar.gz
        - mkdir swift-RELEASE
        - tar xzf swift.tar.gz -C swift-RELEASE --strip-components=1
        - export PATH="${HOME}/swift-RELEASE/usr/bin:${PATH}"
        - cd $TRAVIS_BUILD_DIR
    - os: linux
      dist: bionic
      sudo: required
      install:
        - cd $HOME
        - sudo apt-get install -y clang libicu-dev
        - wget -q -O swift.tar.gz https://swift.org/builds/swift-5.1.5-release/ubuntu1804/swift-5.1.5-RELEASE/swift-5.1.5-RELEASE-ubuntu18.04.tar.gz
        - mkdir swift-RELEASE
        - tar xzf swift.tar.gz -C swift-RELEASE --strip-components=1
        - export PATH="${HOME}/swift-RELEASE/usr/bin:${PATH}"
        - cd $TRAVIS_BUILD_DIR
    - os: linux
      dist: bionic
      sudo: required
      install:
        - cd $HOME
        - sudo apt-get install -y clang libicu-dev
        - wget -q -O swift.tar.gz https://swift.org/builds/swift-5.2.5-release/ubuntu1804/swift-5.2.5-RELEASE/swift-5.2.5-RELEASE-ubuntu18.04.tar.gz
        - mkdir swift-RELEASE
        - tar xzf swift.tar.gz -C swift-RELEASE --strip-components=1
        - export PATH="${HOME}/swift-RELEASE/usr/bin:${PATH}"
        - cd $TRAVIS_BUILD_DIR
    - os: linux
      dist: focal
      sudo: required
      install:
        - cd $HOME
        - sudo apt-get install -y binutils git gnupg2 libc6-dev libcurl4 libedit2 libgcc-9-dev libpython2.7 libsqlite3-0 libstdc++-9-dev libxml2 libz3-dev pkg-config tzdata zlib1g-dev
        - wget -q -O swift.tar.gz https://swift.org/builds/swift-5.3.2-release/ubuntu2004/swift-5.3.2-RELEASE/swift-5.3.2-RELEASE-ubuntu20.04.tar.gz
        - mkdir swift-RELEASE
        - tar xzf swift.tar.gz -C swift-RELEASE --strip-components=1
        - export PATH="${HOME}/swift-RELEASE/usr/bin:${PATH}"
        - cd $TRAVIS_BUILD_DIR
    - os: osx
      sudo: required
      osx_image: xcode12.2
      install:
        - cd $TRAVIS_BUILD_DIR
      after_success:
        - xcodebuild -quiet -enableCodeCoverage YES -scheme ElasticSwift-Package clean build test
        - bash <(curl -s https://codecov.io/bash) -J 'ElasticSwift' -J 'ElasticSwiftCore' -J 'ElasticSwiftCodableUtils' -J 'ElasticSwiftNetworking' -J 'ElasticSwiftQueryDSL' -J 'ElasticSwiftNetworkingNIO'

before_install:
  - cd $HOME
  - wget -q -O elasticsearch.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.12.tar.gz
  - mkdir elasticsearch
  - tar xzf elasticsearch.tar.gz --strip-components=1 -C elasticsearch
  - cd elasticsearch
  - bin/elasticsearch -d -p pid
before_script:
  - sleep 30
  - curl -XGET 'http://localhost:9200'
script:
  - swift build
  - swift test